[llm_response]
response = "'_summary': A customer calls Andrews Bank to investigate a transaction in their debit account, which they don't understand. The representative helps them check the account and eventually resolves the issue., 'call_theme': Account Dispute Resolution"
