[llm_response]
response = "Here is the generated call summary and theme:\n\n'summary': The customer, Mr. Taylor, called to report an unknown transaction in his debit account. He was assisted by a representative who checked his account information and contacted the merchant to investigate the charge.\n\n'call_theme': Customer Service"
